### ISSUE TITLE
template issue

### ISSUE THREAD

**Issue by acagastya** [gsilvapt/pmz#12] opened 2021-11-03 03:28 UTC
Hi, insalled pmz, configured `~/.pmz.yaml` to mention `ztldir: /Users/<username>/zettle` and ran `pmz new`.  It gives the following error.

```
Failed to write template to new note, but it should exist for you.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1102e19]

goroutine 1 [running]:
text/template.errRecover(0xc000117ba0)
	/usr/local/go/src/text/template/exec.go:163 +0x15b
panic({0x12aee20, 0x152e290})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
text/template.(*Template).execute(0x0, {0x135a440, 0xc0000ae0c8}, {0x12b2740, 0x156dd80})
	/usr/local/go/src/text/template/exec.go:214 +0x239
text/template.(*Template).Execute(...)
	/usr/local/go/src/text/template/exec.go:200
github.com/gsilvapt/pmz/cmd.writeToNewNote(0xc0000b4198, {0x0, 0x0})
	/Users/<username>/go/pkg/mod/github.com/gsilvapt/pmz@v0.0.0-20211024185000-aa021a65b9a0/cmd/new.go:90 +0xf1
github.com/gsilvapt/pmz/cmd.glob..func1(0x1534c00, {0x12ec824, 0x0, 0x0})
	/Users/<username>/go/pkg/mod/github.com/gsilvapt/pmz@v0.0.0-20211024185000-aa021a65b9a0/cmd/new.go:52 +0x354
github.com/spf13/cobra.(*Command).execute(0x1534c00, {0x156c970, 0x0, 0x0})
	/Users/<username>/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1534e80)
	/Users/<username>/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/<username>/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/gsilvapt/pmz/cmd.Execute()
	/Users/<username>/go/pkg/mod/github.com/gsilvapt/pmz@v0.0.0-20211024185000-aa021a65b9a0/cmd/root.go:50 +0x25
main.main()
	/Users/<username>/go/pkg/mod/github.com/gsilvapt/pmz@v0.0.0-20211024185000-aa021a65b9a0/main.go:21 +0x17
```

It created `/Users/<username>/zettle/2021113316/README.md`, but well, it did not open the directory or the file.  I did not find anything in readme, though inspecting the source suggests it is expecting a template file for the zettle readme?  Can you please update the readme to suggest how it should be used?

**Comment by gsilvapt** [comment] 2021-11-03 08:26
Hi @acagastya,

Thank you very much for your report. I'm using `text/template` here and I just learn it does not get included in the compiled binary. Will try to find a solution and fix this one.

**Comment by gsilvapt** [comment] 2021-11-03 08:50
Can you try installing the latest binaries, please? I tried reproducing locally but could not do it. I noticed this issue before because I was not using the seconds as directory name, but I think that got fixed in #11.

**Comment by acagastya** [comment] 2021-11-03 09:17
I tried with the latest one, still seems to be causing the same issue.

Re the files:

Recently I rewrote a project in golang which expects few files to be present, and I suggest users to clone the repo to have all files -- I will just try cloning pmz, because that should work just fine, I feel.

**Comment by gsilvapt** [comment] 2021-11-03 09:29
That's true, I read about it online too. Need to figure out a way to
include the templates in the packaged binary then.

Thanks again for your help

**Comment by acagastya** [comment] 2021-11-03 09:30
https://github.com/gsilvapt/pmz/blob/main/cmd/new.go#L85
I think instead of hardcoding, there should be an option to provide this as a parameter to command line option?  That might be a breaking change, but that way we can run the binary from any way?  (Temporary work around could be I hard code in it and recompile it.)

What would you suggest?

**Comment by gsilvapt** [comment] 2021-11-03 13:34
I like your suggesting; the templates could be provided by the user. It has some further implications, like more documentation to write on how to use the templates, mandatory variables etc.

From what I read online, seems people are hardcoding tempaltes or declaring them as global variables. This would force the template to exist at runtime.

**Closed** 2021-11-08 11:39 UTC
Labels: bug
